services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odoo"]
      interval: 5s
      timeout: 5s
      retries: 10

  odoo:
    image: odoo:19
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8069:8069"
    volumes:
      - ./odoo.conf:/etc/odoo/odoo.conf:ro
      - ./addons:/mnt/extra-addons
      # If you have Enterprise, mount it too:
      - ./enterprise:/mnt/enterprise
    environment:
      HOST: db
      USER: odoo
      PASSWORD: odoo
    command: [
      "odoo", "-c", "/etc/odoo/odoo.conf",
      "--dev=reload,qweb,xml"  # better DX while coding
    ]

volumes:
  db-data:

